version: '3'

volumes:
  sprintable-gem-cache:

networks:
  sprintable:

services:
  postgres:
    container_name: sprintable-postgres
    image: postgres:10.5-alpine
    ports:
      - '5432:5432'
    networks:
      - sprintable

  redis:
    container_name: sprintable-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - sprintable

volumes:
  sprintable-app:
  sprintable-gem-cache:
