version: '3'

networks:
  commmit:

services:
  postgres:
    container_name: commmit-postgres
    image: postgres:10-alpine
    ports:
      - '9876:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - commmit

  redis:
    container_name: commmit-redis
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - '6789:6379'
    networks:
      - commmit

  meilisearch:
    container_name: commmit-meilisearch
    image: getmeili/meilisearch:v0.20.0
    volumes:
      - meilidata:/data.ms
    ports:
      - '7700:7700'
    networks:
      - commmit
    environment:
      - MEILI_MASTER_KEY=0a62e145-b3ec-4a64-b3f5-54c5adf7dbac

volumes:
  pgdata:
  redisdata:
  meilidata:
