development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TLS_URL") { ENV.fetch("REDIS_URL") } %>
  channel_prefix: commmit_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TLS_URL") { ENV.fetch("REDIS_URL") } %>
  channel_prefix: commmit_production
